/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naveen kumar
 */
public class dbms23 extends javax.swing.JFrame {
String s,s1,s2,s3;
int i=0;
    /**
     * Creates new form dbms23
     * @param s
     */
    public dbms23(String s) {
        initComponents();
        this.s=s;
          SQL d=new SQL("jdbc:oracle:thin:@localhost:1521:XE","oracle.jdbc.OracleDriver","hr","hr");
        String str="select gsid,gcno,sname from dbgrade,dbstud where gfid='"+s+"' and dbgrade.gsid=dbstud.sid";
   try{
        d.executeQuery(str);
        
          while (d.rs.next())
          {
           if(i==0)
           {
           s1=d.rs.getString("gsid");
           s2= d.rs.getString("sname");
           s3=d.rs.getString("gcno");
           l11.setText(s1);
           l12.setText(s2);
           l13.setText(s3);
           i++;
           }
           else if(i==1)
           {
           s1=d.rs.getString("gsid");
           s2= d.rs.getString("sname");
           s3=d.rs.getString("gcno");
           l21.setText(s1);
           l22.setText(s2);
           l23.setText(s3);
           i++;
           }
           else if(i==2)
           {
           s1=d.rs.getString("gsid");
           s2= d.rs.getString("sname");
           s3=d.rs.getString("gcno");
           l31.setText(s1);
           l32.setText(s2);
           l33.setText(s3);
           i++;
           }
           else if(i==3)
           {
           s1=d.rs.getString("gsid");
           s2= d.rs.getString("sname");
           s3=d.rs.getString("gcno");
           l41.setText(s1);
           l42.setText(s2);
           l43.setText(s3);
           i++;
           }
           else if(i==4)
           {
           s1=d.rs.getString("gsid");
           s2= d.rs.getString("sname");
           s3=d.rs.getString("gcno");
           l51.setText(s1);
           l52.setText(s2);
           l53.setText(s3);
           i++;
           }
           else if(i==4)
           {
           s1=d.rs.getString("gsid");
           s2= d.rs.getString("sname");
           s3=d.rs.getString("gcno");
           l51.setText(s1);
           l52.setText(s2);
           l53.setText(s3);
           i++;
           }
           else if(i==5)
           {
           s1=d.rs.getString("gsid");
           s2= d.rs.getString("sname");
           s3=d.rs.getString("gcno");
           l61.setText(s1);
           l62.setText(s2);
           l63.setText(s3);
           i++;
           }
           else if(i==6)
           {
           s1=d.rs.getString("gsid");
           s2= d.rs.getString("sname");
           s3=d.rs.getString("gcno");
           l71.setText(s1);
           l72.setText(s2);
           l73.setText(s3);
           i++;
           }
          /* else if(i==7)
           {
           s1=d.rs.getString("gsid");
           s2= d.rs.getString("sname");
           s3=d.rs.getString("gcno");
           l81.setText(s1);
           l82.setText(s2);
           l83.setText(s3);
           i++;
           }*/
          }
   }
    catch(Exception e)
    {
        
    }
         
    }

    private dbms23() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        l41 = new javax.swing.JLabel();
        l42 = new javax.swing.JLabel();
        l43 = new javax.swing.JLabel();
        l51 = new javax.swing.JLabel();
        l52 = new javax.swing.JLabel();
        l53 = new javax.swing.JLabel();
        l61 = new javax.swing.JLabel();
        l62 = new javax.swing.JLabel();
        l63 = new javax.swing.JLabel();
        l71 = new javax.swing.JLabel();
        l72 = new javax.swing.JLabel();
        l73 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 21, 108));
        jLabel1.setText("Student Reg no");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 40, 170, 40);

        jLabel2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 21, 108));
        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 40, 150, 40);

        jLabel3.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 21, 108));
        jLabel3.setText("Course code");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(620, 40, 140, 40);

        l11.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l11);
        l11.setBounds(220, 130, 180, 40);

        l12.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l12);
        l12.setBounds(420, 130, 150, 40);

        l13.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l13);
        l13.setBounds(630, 130, 150, 40);

        l21.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l21);
        l21.setBounds(220, 190, 180, 40);

        l22.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l22);
        l22.setBounds(420, 190, 150, 40);

        l23.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l23);
        l23.setBounds(630, 190, 150, 40);

        l31.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l31);
        l31.setBounds(220, 250, 180, 40);

        l32.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l32);
        l32.setBounds(420, 250, 150, 40);

        l33.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l33);
        l33.setBounds(630, 250, 150, 40);

        l41.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l41);
        l41.setBounds(220, 310, 180, 40);

        l42.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l42);
        l42.setBounds(420, 310, 150, 40);

        l43.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l43);
        l43.setBounds(630, 310, 150, 40);

        l51.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l51);
        l51.setBounds(220, 370, 180, 40);

        l52.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l52);
        l52.setBounds(420, 370, 150, 40);

        l53.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l53);
        l53.setBounds(630, 370, 150, 40);

        l61.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l61);
        l61.setBounds(220, 430, 180, 40);

        l62.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l62);
        l62.setBounds(420, 430, 150, 40);

        l63.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l63);
        l63.setBounds(630, 430, 150, 40);

        l71.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l71);
        l71.setBounds(220, 490, 180, 40);

        l72.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l72);
        l72.setBounds(420, 490, 150, 40);

        l73.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l73);
        l73.setBounds(630, 490, 150, 40);

        jButton1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 560, 190, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pink_shades-2560x1600.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 10, 1060, 650);

        setBounds(0, 0, 1069, 683);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dbms22 d22=new dbms22(s);
       d22.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dbms23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dbms23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dbms23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dbms23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dbms23().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l31;
    private javax.swing.JLabel l32;
    private javax.swing.JLabel l33;
    private javax.swing.JLabel l41;
    private javax.swing.JLabel l42;
    private javax.swing.JLabel l43;
    private javax.swing.JLabel l51;
    private javax.swing.JLabel l52;
    private javax.swing.JLabel l53;
    private javax.swing.JLabel l61;
    private javax.swing.JLabel l62;
    private javax.swing.JLabel l63;
    private javax.swing.JLabel l71;
    private javax.swing.JLabel l72;
    private javax.swing.JLabel l73;
    // End of variables declaration//GEN-END:variables

}
