
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naveen kumar
 */
public class dbms34 extends javax.swing.JFrame {
String s,s1,s2,s3;
int n=0,m;
    /**
     * Creates new form dbms34
     */
    public dbms34() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        l.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 36)); // NOI18N
        l.setText("Faculty Information");
        getContentPane().add(l);
        l.setBounds(360, 50, 380, 60);

        jLabel2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        jLabel2.setText("Faculty ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 200, 160, 40);

        jLabel3.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        jLabel3.setText("Faculty Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 290, 170, 40);

        jLabel4.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        jLabel4.setText("Faculty Password :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 370, 202, 50);

        t.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(t);
        t.setBounds(440, 200, 330, 50);

        t1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(440, 280, 330, 50);

        t2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(440, 370, 330, 50);

        jButton4.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 470, 140, 50);

        jButton6.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        jButton6.setText("<<Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(530, 560, 140, 50);

        jButton7.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        jButton7.setText("Reset");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(620, 470, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leopard_aurora_purple-1680x1050.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 650);

        setBounds(0, 0, 1069, 683);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        t.setText("");
       t1.setText("");
       t2.setText("");
       JOptionPane.showMessageDialog(null,"Enter the Faculty information");
      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         s=t.getText();
        s1=t1.getText();
        s2=t2.getText();
        
      if(s.equals("")||s1.equals("")||s2.equals(""))
     {
         JOptionPane.showMessageDialog(null,"please!! Enter the values" );
      }
      
       SQL d=new SQL("jdbc:oracle:thin:@localhost:1521:XE","oracle.jdbc.OracleDriver","hr","hr");
        String str="insert into dbfaclty values('"+s+"','"+s1+"','"+s2+"')";
   try{
       
        d.executeQuery(str);
      
            d.rs.next();
            n=1;
          JOptionPane.showMessageDialog(null,"Faculty information Successfully updated");
            t.setText("");
            t1.setText("");
            t2.setText("");
            JOptionPane.showMessageDialog(null,"Enter the Faculty information");
   }
   
   
   catch(Exception e)
   { 
     
  }  
 
      
       
      
   
               
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       dbms33 d33=new dbms33();
       d33.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dbms34.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dbms34.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dbms34.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dbms34.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dbms34().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l;
    private javax.swing.JTextField t;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
