
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naveen kumar
 */
public class dbms22 extends javax.swing.JFrame {
String s,s1,s2,s3,f;
int  n,m;
    /**
     * Creates new form dbms22
     * @param s
     */
    public dbms22(String s) {
        initComponents();
        this.s=s;
        p.setVisible(false);
    }

    dbms22() {
         //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        c = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        p.setBackground(new java.awt.Color(51, 140, 216));
        p.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel2.setText("Register number :");
        p.add(jLabel2);
        jLabel2.setBounds(100, 110, 146, 30);

        jButton2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p.add(jButton2);
        jButton2.setBounds(470, 480, 150, 50);

        t1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        p.add(t1);
        t1.setBounds(270, 290, 290, 50);

        jLabel3.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel3.setText("course number :");
        p.add(jLabel3);
        jLabel3.setBounds(110, 190, 132, 30);

        jButton3.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        p.add(jButton3);
        jButton3.setBounds(310, 480, 140, 50);

        c.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        c.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SWE201", "SWE202","SWE203","SWE301","SWE302","SWE303"}));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        p.add(c);
        c.setBounds(270, 190, 290, 50);

        jButton5.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        p.add(jButton5);
        jButton5.setBounds(600, 290, 70, 50);

        jLabel4.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel4.setText("Mark :");
        p.add(jLabel4);
        jLabel4.setBounds(170, 300, 54, 30);

        l.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        l.setText("Give the following information to update grade and marks");
        p.add(l);
        l.setBounds(140, 10, 500, 40);

        jButton1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p.add(jButton1);
        jButton1.setBounds(140, 480, 140, 50);

        jLabel5.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel5.setText("Grade :");
        p.add(jLabel5);
        jLabel5.setBounds(170, 390, 61, 30);

        t.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        p.add(t);
        t.setBounds(270, 110, 290, 50);

        l2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        p.add(l2);
        l2.setBounds(270, 380, 200, 50);

        getContentPane().add(p);
        p.setBounds(150, 110, 730, 550);

        l1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(290, 380, 0, 0);

        jButton4.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 30, 180, 49);

        jButton6.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        jButton6.setText("Student Info");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(560, 30, 180, 49);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/water_sparkle-wide.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1060, 670);

        setBounds(0, 0, 1069, 704);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      dbms1 d1=new dbms1();
      d1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        s1=(String) c.getSelectedItem();
    }//GEN-LAST:event_cActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       f=t1.getText();
       l1.setText("");
       m=Integer.parseInt(f);
       if(m<40)
       {
           l2.setText("F");
       }
       else if(m>=40 && m<50)
       {
           l2.setText("E");
       }
          else if(m>=50 && m<60)
       {
           l2.setText("D");
       }
          else if(m>=60 && m<70)
       {
           l2.setText("C");
       }
      else if(m>=70 && m<80)
       {
           l2.setText("B");
       }
      else if(m>=80 && m<90)
       {
           l2.setText("A");
       }
       else if(m>=90 && m<101)
       {
           l2.setText("S");
       }
       else
       {
            JOptionPane.showMessageDialog(null,"Invalid mark");
            l2.setText("");
            t1.setText("");
            
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        s2=t.getText();
        //s-faculty ID
        s3=l2.getText();
        n=Integer.parseInt(s);
       if(s2.equals("")||s3.equals("")||s1.equals("")||f.equals(""))
       {
             JOptionPane.showMessageDialog(null,"Please!! Enter the values");
       }
       else
       {
        
        SQL d=new SQL("jdbc:oracle:thin:@localhost:1521:XE","oracle.jdbc.OracleDriver","hr","hr");
        String str="insert into dbgrade values('"+s2+"','"+s+"','"+s1+"',"+m+",'"+s3+"')";
   try{
        d.executeQuery(str);
        
            d.rs.next();
             JOptionPane.showMessageDialog(null,"Marks and Grade are Successfully updated");
            //l.setText("Marks and Grade are Successfully updated");
              l1.setText("");
              t1.setText("");
              t.setText("");
   }
   catch(Exception e)
   {
       l.setText("Error in your Entry");
   }
       }
          
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       t.setText("");
       t1.setText("");
       l1.setText("");
       l.setText("Give the following information");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       p.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       dbms23 d23=new dbms23(s);
       d23.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dbms22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dbms22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dbms22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dbms22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dbms22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JPanel p;
    private javax.swing.JTextField t;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
