
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListDataListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naveen kumar
 */
public class dbms12 extends javax.swing.JFrame {
String s;
 String s1,s2,s3;
int m;

    /**
     * Creates new form dbms12
     * @param s
     */
    public dbms12(String s) {
        initComponents();
        this.s=s;
    }

    private dbms12() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        t = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        l5.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        l5.setText("Enter the course code to retrive the mark and Grade");
        getContentPane().add(l5);
        l5.setBounds(250, 40, 580, 40);

        jLabel2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel2.setText("Course code");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 180, 170, 40);

        l2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(440, 340, 250, 40);

        l.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        getContentPane().add(l);
        l.setBounds(290, 340, 120, 40);

        l1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(290, 400, 120, 40);

        l3.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(440, 400, 240, 40);

        jButton2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 510, 150, 50);

        jButton3.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jButton3.setText("Course Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 510, 150, 50);

        t.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(t);
        t.setBounds(430, 180, 240, 50);

        jButton1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 180, 70, 50);

        jLabel1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel1.setText("eg : SWE201");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 260, 180, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blurred_colors-1920x1200 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1050, 650);

        setBounds(0, 0, 1069, 683);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        dbms1 d1=new dbms1();
        d1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
              dbms13 d13=new dbms13(s);
              d13.setVisible(true);
             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            s1=t.getText();
        SQL d=new SQL("jdbc:oracle:thin:@localhost:1521:XE","oracle.jdbc.OracleDriver","hr","hr");
        String str="select mark,grade from dbgrade where gsid='"+s+"' and gcno='"+s1+"' ";
   try{
        d.executeQuery(str);
        
            d.rs.next();
          
           m= d.rs.getInt("mark");
           s2=d.rs.getString("grade");
           l.setText("Mark :");
           l1.setText("Grade :");
           l2.setText(Integer.toString(m));
           l3.setText(s2);
   } 
   catch(Exception e)
   {
         
                l5.setText("Please!! Select the correct Course code!!");
                l.setText("");
                l1.setText("");
                l2.setText("");
                l3.setText("");
          
   }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dbms12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dbms12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dbms12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dbms12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dbms12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
