/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naveen kumar
 */
public class dbms13 extends javax.swing.JFrame {
String s,s1,s2,s3;
int i=0;
    /**
     * Creates new form dbms13
     */
    public dbms13(String s) {
        initComponents();
        this.s=s;
        SQL d=new SQL("jdbc:oracle:thin:@localhost:1521:XE","oracle.jdbc.OracleDriver","hr","hr");
        String str="select cno,cname,fname from dbcours,dbfaclty where dbcours.cfacid=dbfaclty.fid";
   try{
        d.executeQuery(str);
        
          while (d.rs.next())
          {
           if(i==0)
           {
           s1=d.rs.getString("cno");
           s2= d.rs.getString("cname");
           s3=d.rs.getString("fname");
           l11.setText(s1);
           l12.setText(s2);
           l13.setText(s3);
           i++;
          }
           else if(i==1)
           {
           s1=d.rs.getString("cno");
           s2= d.rs.getString("cname");
           s3=d.rs.getString("fname");
           l21.setText(s1);
           l22.setText(s2);
           l23.setText(s3);
           i++;
          }
           else if(i==2)
           {
           s1=d.rs.getString("cno");
           s2= d.rs.getString("cname");
           s3=d.rs.getString("fname");
           l31.setText(s1);
           l32.setText(s2);
           l33.setText(s3);
           i++;
          }
           else if(i==3)
           {
           s1=d.rs.getString("cno");
           s2= d.rs.getString("cname");
           s3=d.rs.getString("fname");
           l41.setText(s1);
           l42.setText(s2);
           l43.setText(s3);
           i++;
          }
          else if(i==4)
           {
           s1=d.rs.getString("cno");
           s2= d.rs.getString("cname");
           s3=d.rs.getString("fname");
           l51.setText(s1);
           l52.setText(s2);
           l53.setText(s3);
           i++;
          }
           else if(i==5)
           {
           s1=d.rs.getString("cno");
           s2= d.rs.getString("cname");
           s3=d.rs.getString("fname");
           l61.setText(s1);
           l62.setText(s2);
           l63.setText(s3);
           i++;
          }
        else if(i==6)
           {
           s1=d.rs.getString("cno");
           s2= d.rs.getString("cname");
           s3=d.rs.getString("fname");
           l71.setText(s1);
           l72.setText(s2);
           l73.setText(s3);
           i++;
          }
    }
   }
   catch(Exception e)
   {
        
   }
   
   }
    private dbms13() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        l41 = new javax.swing.JLabel();
        l42 = new javax.swing.JLabel();
        l43 = new javax.swing.JLabel();
        l51 = new javax.swing.JLabel();
        l52 = new javax.swing.JLabel();
        l53 = new javax.swing.JLabel();
        l61 = new javax.swing.JLabel();
        l62 = new javax.swing.JLabel();
        l63 = new javax.swing.JLabel();
        l71 = new javax.swing.JLabel();
        l72 = new javax.swing.JLabel();
        l73 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 24, 96));
        jLabel1.setText("Course ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 80, 149, 50);

        jLabel2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(24, 24, 96));
        jLabel2.setText("Course Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 80, 130, 50);

        jLabel3.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 24, 96));
        jLabel3.setText("Faculty ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 80, 120, 50);

        l11.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l11);
        l11.setBounds(280, 150, 140, 30);

        l12.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l12);
        l12.setBounds(450, 150, 180, 30);

        l13.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l13);
        l13.setBounds(660, 150, 180, 30);

        l21.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l21);
        l21.setBounds(280, 210, 140, 30);

        l22.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l22);
        l22.setBounds(450, 210, 180, 30);

        l23.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l23);
        l23.setBounds(660, 210, 180, 30);

        l31.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l31);
        l31.setBounds(280, 270, 140, 30);

        l32.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l32);
        l32.setBounds(450, 270, 180, 30);

        l33.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l33);
        l33.setBounds(660, 270, 180, 30);

        l41.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l41);
        l41.setBounds(280, 330, 140, 30);

        l42.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l42);
        l42.setBounds(450, 330, 180, 30);

        l43.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l43);
        l43.setBounds(660, 330, 180, 30);

        l51.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l51);
        l51.setBounds(280, 390, 140, 30);

        l52.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l52);
        l52.setBounds(450, 390, 180, 30);

        l53.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l53);
        l53.setBounds(660, 390, 180, 30);

        l61.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l61);
        l61.setBounds(280, 450, 140, 30);

        l62.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l62);
        l62.setBounds(450, 450, 180, 30);

        l63.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l63);
        l63.setBounds(660, 450, 180, 30);

        l71.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l71);
        l71.setBounds(280, 510, 140, 30);

        l72.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l72);
        l72.setBounds(450, 510, 180, 30);

        l73.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        getContentPane().add(l73);
        l73.setBounds(660, 510, 180, 30);

        jButton1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 580, 130, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pink_shades-2560x1600.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1060, 650);

        setBounds(0, 0, 1069, 683);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dbms12 d12=new dbms12(s);;
        d12.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dbms13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dbms13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dbms13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dbms13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dbms13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l31;
    private javax.swing.JLabel l32;
    private javax.swing.JLabel l33;
    private javax.swing.JLabel l41;
    private javax.swing.JLabel l42;
    private javax.swing.JLabel l43;
    private javax.swing.JLabel l51;
    private javax.swing.JLabel l52;
    private javax.swing.JLabel l53;
    private javax.swing.JLabel l61;
    private javax.swing.JLabel l62;
    private javax.swing.JLabel l63;
    private javax.swing.JLabel l71;
    private javax.swing.JLabel l72;
    private javax.swing.JLabel l73;
    // End of variables declaration//GEN-END:variables
}
